## Unit Vector

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [5]:
df['species'].replace(['setosa','versicolor','virginica'],[1,2,3],inplace = True)

In [6]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [7]:
df['species'].value_counts()

1    50
2    50
3    50
Name: species, dtype: int64

In [8]:
from sklearn.preprocessing import normalize

In [9]:
df1 = normalize(df)

In [10]:
df1

array([[0.79397269, 0.54488322, 0.21795329, 0.03113618, 0.15568092],
       [0.81655326, 0.49993057, 0.23330093, 0.0333287 , 0.16664352],
       [0.79376492, 0.54043569, 0.219552  , 0.03377723, 0.16888615],
       [0.78819833, 0.53117713, 0.25702119, 0.03426949, 0.17134746],
       [0.78125   , 0.5625    , 0.21875   , 0.03125   , 0.15625   ],
       [0.7760351 , 0.5604698 , 0.24430735, 0.05748408, 0.1437102 ],
       [0.76912754, 0.56848557, 0.23408229, 0.05016049, 0.16720164],
       [0.79205591, 0.53859802, 0.23761677, 0.03168224, 0.15841118],
       [0.79321137, 0.5227984 , 0.25238543, 0.03605506, 0.18027531],
       [0.80686453, 0.51046531, 0.24699935, 0.01646662, 0.16466623],
       [0.79497773, 0.54470697, 0.22082715, 0.02944362, 0.1472181 ],
       [0.77662176, 0.55010708, 0.25887392, 0.03235924, 0.1617962 ],
       [0.8112322 , 0.50702013, 0.23660939, 0.01690067, 0.16900671],
       [0.78889123, 0.55038923, 0.20180939, 0.01834631, 0.18346308],
       [0.80338883, 0.55406126, 0.16621838, 0.02770306, 0.13851532],
       [0.7667776 , 0.5918985 , 0.20178358, 0.05380895, 0.13452239],
       [0.78583392, 0.56754672, 0.18918224, 0.05820992, 0.1455248 ],
       [0.79349205, 0.54455337, 0.21782135, 0.046676  , 0.15558668],
       [0.79886484, 0.53257656, 0.23825793, 0.04204552, 0.14015173],
       [0.77069529, 0.57424355, 0.22667508, 0.04533502, 0.15111672],
       [0.80813335, 0.5088247 , 0.25441235, 0.02993086, 0.14965432],
       [0.77674983, 0.56352438, 0.22845583, 0.06092155, 0.15230389],
       [0.76496862, 0.59867109, 0.16629753, 0.03325951, 0.16629753],
       [0.79609794, 0.5151222 , 0.26536598, 0.07804882, 0.15609764],
       [0.76616341, 0.54269908, 0.30327302, 0.03192348, 0.15961738],
       [0.81541009, 0.48924605, 0.26093123, 0.0326164 , 0.16308202],
       [0.78781686, 0.53571547, 0.2521014 , 0.06302535, 0.15756337],
       [0.79689392, 0.53637091, 0.22987325, 0.03064977, 0.15324883],
       [0.80622577, 0.52714762, 0.21706079, 0.03100868, 0.15504342],
       [0.78409602, 0.53385261, 0.2669263 , 0.03336579, 0.16682894],
       [0.79723661, 0.51488198, 0.26574554, 0.03321819, 0.16609096],
       [0.81288067, 0.51181375, 0.22580019, 0.06021338, 0.15053346],
       [0.75761191, 0.59734785, 0.2185419 , 0.01456946, 0.1456946 ],
       [0.77098595, 0.58875291, 0.19625097, 0.02803585, 0.14017926],
       [0.80653656, 0.51025782, 0.24689895, 0.03291986, 0.1645993 ],
       [0.81411201, 0.52103169, 0.19538688, 0.03256448, 0.1628224 ],
       [0.81780431, 0.52042093, 0.1932992 , 0.02973834, 0.14869169],
       [0.77533975, 0.56963737, 0.22152564, 0.01582326, 0.1582326 ],
       [0.78911866, 0.53803545, 0.2331487 , 0.03586903, 0.17934515],
       [0.79784953, 0.53189969, 0.23466163, 0.03128822, 0.15644108],
       [0.79027312, 0.55319118, 0.20547101, 0.04741639, 0.15805462],
       [0.84560178, 0.43219647, 0.24428496, 0.05637345, 0.18791151],
       [0.77383759, 0.56279098, 0.22863383, 0.03517444, 0.17587218],
       [0.77925495, 0.54547847, 0.24936158, 0.09351059, 0.15585099],
       [0.75841148, 0.56509091, 0.28254545, 0.05948325, 0.14870813],
       [0.81030693, 0.50644183, 0.23633952, 0.05064418, 0.16881394],
       [0.76841745, 0.57254634, 0.24107214, 0.03013402, 0.15067009],
       [0.78429349, 0.54559547, 0.23869802, 0.03409972, 0.17049858],
       [0.78946356, 0.55113494, 0.22343308, 0.02979108, 0.14895539],
       [0.80177227, 0.5291697 , 0.22449624, 0.03207089, 0.16035445],
       [0.74923109, 0.34250564, 0.50305516, 0.14984622, 0.21406603],
       [0.72605491, 0.36302745, 0.51050736, 0.17016912, 0.22689216],
       [0.73772534, 0.33144182, 0.52389191, 0.16037507, 0.21383343],
       [0.72702746, 0.30402967, 0.52874725, 0.17184285, 0.26437362],
       [0.73835038, 0.31805863, 0.52252489, 0.17038855, 0.22718473],
       [0.70019075, 0.34395335, 0.55278217, 0.15969263, 0.24568097],
       [0.70777582, 0.37073972, 0.52802323, 0.17975259, 0.22469074],
       [0.72515046, 0.35517574, 0.48836664, 0.14798989, 0.29597978],
       [0.74340542, 0.32664783, 0.51813105, 0.14642834, 0.22527437],
       [0.6980023 , 0.36242427, 0.52350172, 0.1879237 , 0.26846242],
       [0.73521462, 0.29408585, 0.51465024, 0.14704292, 0.29408585],
       [0.7170636 , 0.36460861, 0.51045205, 0.18230431, 0.24307241],
       [0.7629859 , 0.2797615 , 0.50865726, 0.12716432, 0.25432863],
       [0.71069703, 0.33787236, 0.54758624, 0.16311079, 0.23301542],
       [0.73266805, 0.37941738, 0.47100089, 0.17008365, 0.26166716],
       [0.74992692, 0.34698111, 0.49248932, 0.15670115, 0.22385878],
       [0.68486479, 0.36689185, 0.55033778, 0.18344593, 0.24459457],
       [0.73224386, 0.34087214, 0.51762066, 0.12624894, 0.25249788],
       [0.74220898, 0.26336448, 0.53870007, 0.17956669, 0.23942225],
       [0.73512593, 0.32818122, 0.5119627 , 0.14439974, 0.26254497],
       [0.67977944, 0.36869394, 0.5530409 , 0.20739034, 0.23043371],
       [0.74668381, 0.34274011, 0.48962873, 0.15912934, 0.24481436],
       [0.72171057, 0.28639308, 0.56133044, 0.17183585, 0.22911447],
       [0.71601373, 0.32866204, 0.55168271, 0.14085516, 0.2347586 ],
       [0.74625737, 0.33814787, 0.50139167, 0.15158353, 0.23320543],
       [0.74787836, 0.33994471, 0.49858557, 0.15864086, 0.2266298 ],
       [0.74603752, 0.30719192, 0.52661472, 0.15359596, 0.2194228 ],
       [0.72340546, 0.32391289, 0.53985482, 0.18355064, 0.21594193],
       [0.71252074, 0.34438502, 0.53439055, 0.17813018, 0.23750691],
       [0.75831672, 0.34589885, 0.46563307, 0.13303802, 0.26607604],
       [0.73720978, 0.32169154, 0.50934494, 0.14744196, 0.26807628],
       [0.74365076, 0.32450215, 0.50027415, 0.13520923, 0.27041846],
       [0.73910842, 0.34406771, 0.4969867 , 0.15291898, 0.25486497],
       [0.68888199, 0.3099969 , 0.58554969, 0.18370186, 0.22962733],
       [0.67154622, 0.37308123, 0.55962185, 0.18654062, 0.24872082],
       [0.69574863, 0.39425756, 0.52181147, 0.18553297, 0.23191621],
       [0.73613041, 0.34059765, 0.51638999, 0.16480532, 0.21974042],
       [0.75283272, 0.27484369, 0.52578793, 0.15534643, 0.23899451],
       [0.70631892, 0.37838513, 0.51712635, 0.16396689, 0.25225676],
       [0.72100539, 0.32772972, 0.52436756, 0.17041946, 0.26218378],
       [0.69957345, 0.33070745, 0.55965876, 0.15263421, 0.25439034],
       [0.71234272, 0.35033249, 0.53717648, 0.16348849, 0.23355499],
       [0.73755303, 0.33062722, 0.50865726, 0.15259718, 0.25432863],
       [0.73577163, 0.33845495, 0.48560928, 0.14715433, 0.29430865],
       [0.71131545, 0.34295566, 0.53348659, 0.1651268 , 0.25404123],
       [0.70934819, 0.37334115, 0.52267761, 0.14933646, 0.2488941 ],
       [0.71122317, 0.36185038, 0.52405918, 0.16220879, 0.24955199],
       [0.73564923, 0.34409399, 0.51020833, 0.15424903, 0.2373062 ],
       [0.74814166, 0.36673611, 0.44008333, 0.16136389, 0.29338889],
       [0.71910337, 0.35324376, 0.51724979, 0.16400603, 0.25231697],
       [0.62431343, 0.32702132, 0.59458422, 0.24774342, 0.29729211],
       [0.65029124, 0.30272178, 0.57180781, 0.21302644, 0.33635754],
       [0.68437113, 0.2891709 , 0.56870277, 0.20241963, 0.2891709 ],
       [0.65789393, 0.30284006, 0.58479461, 0.1879697 , 0.31328283],
       [0.65416724, 0.30192334, 0.58371846, 0.22141045, 0.30192334],
       [0.68324441, 0.26970174, 0.59334383, 0.18879122, 0.26970174],
       [0.62030286, 0.31648105, 0.56966589, 0.21520712, 0.37977726],
       [0.68481988, 0.27205173, 0.59100893, 0.1688597 , 0.28143283],
       [0.68021181, 0.25381038, 0.58884007, 0.18274347, 0.30457245],
       [0.66490187, 0.33245093, 0.56331964, 0.2308687 , 0.27704244],
       [0.67952089, 0.33453336, 0.53316254, 0.20908335, 0.31362502],
       [0.67858928, 0.28627985, 0.56195675, 0.20145619, 0.31808873],
       [0.68377114, 0.30166374, 0.55305019, 0.21116462, 0.30166374],
       [0.65067476, 0.28538367, 0.57076733, 0.22830693, 0.3424604 ],
       [0.6395287 , 0.30873799, 0.5623442 , 0.26463257, 0.33079071],
       [0.66158927, 0.33079464, 0.54787861, 0.23775864, 0.31011997],
       [0.67135292, 0.30985519, 0.56806786, 0.18591312, 0.30985519],
       [0.66903425, 0.33017275, 0.58214668, 0.19115264, 0.26066269],
       [0.68072324, 0.2298546 , 0.60999875, 0.20333292, 0.26521685],
       [0.68336421, 0.25056688, 0.56947017, 0.17084105, 0.3416821 ],
       [0.67456061, 0.3128397 , 0.55724572, 0.22485354, 0.29328722],
       [0.64147841, 0.32073921, 0.56129361, 0.22909943, 0.34364915],
       [0.68865385, 0.25041958, 0.59921828, 0.17887113, 0.26830669],
       [0.6905587 , 0.29595373, 0.53710121, 0.19730249, 0.32883748],
       [0.66444193, 0.32726245, 0.5652715 , 0.20825792, 0.29751131],
       [0.6854967 , 0.3046652 , 0.57124725, 0.17137418, 0.28562363],
       [0.68651982, 0.31004121, 0.53149922, 0.19931221, 0.33218701],
       [0.67175077, 0.33036923, 0.53960307, 0.19822154, 0.33036923],
       [0.66162462, 0.28946077, 0.57892154, 0.21709558, 0.31013654],
       [0.69919391, 0.2913308 , 0.56323954, 0.15537642, 0.2913308 ],
       [0.69792689, 0.26408044, 0.57531811, 0.17919744, 0.28294333],
       [0.6907273 , 0.33224857, 0.55957654, 0.17486767, 0.2623015 ],
       [0.6601096 , 0.28879795, 0.5775959 , 0.22691267, 0.30942637],
       [0.68417662, 0.3040785 , 0.55385727, 0.1628992 , 0.32579839],
       [0.65667367, 0.27989369, 0.60284796, 0.15071199, 0.32295426],
       [0.70352647, 0.27410122, 0.55733915, 0.21014427, 0.27410122],
       [0.63845158, 0.34456117, 0.56751251, 0.24321965, 0.30402456],
       [0.66343511, 0.32135138, 0.57013955, 0.18659112, 0.31098521],
       [0.66964953, 0.33482477, 0.53571962, 0.20089486, 0.33482477],
       [0.69072564, 0.31032601, 0.54056789, 0.21022085, 0.3003155 ],
       [0.66793261, 0.30904345, 0.55827203, 0.23925944, 0.2990743 ],
       [0.6987185 , 0.31391701, 0.51644411, 0.23290617, 0.30379065],
       [0.65029124, 0.30272178, 0.57180781, 0.21302644, 0.33635754],
       [0.66178677, 0.31142907, 0.57419735, 0.22383964, 0.29196475],
       [0.65851045, 0.32434097, 0.56022531, 0.24571285, 0.29485543],
       [0.68661093, 0.30743773, 0.53289207, 0.23570226, 0.30743773],
       [0.689235  , 0.27350595, 0.5470119 , 0.20786452, 0.32820714],
       [0.68030201, 0.31398554, 0.54424161, 0.20932369, 0.31398554],
       [0.64136025, 0.35171368, 0.55860408, 0.23792396, 0.3103356 ],
       [0.65130776, 0.33117344, 0.56299485, 0.19870406, 0.33117344]])

In [11]:
import pandas as pd

In [12]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [13]:
df1 = pd.DataFrame(df1,columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'])

In [14]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width   species
0      0.793973     0.544883      0.217953     0.031136  0.155681
1      0.816553     0.499931      0.233301     0.033329  0.166644
2      0.793765     0.540436      0.219552     0.033777  0.168886
3      0.788198     0.531177      0.257021     0.034269  0.171347
4      0.781250     0.562500      0.218750     0.031250  0.156250